Term dashboard backup
yeuem1vannam/Minerva pull request #20
Opened 2019-07-02 20:10 UTC by dutavi

### Resolves #

### Proposed Changes

- [ ] Refactor code of God
- [ ]
- [ ]

2019-07-03 06:03 UTC, yeuem1vannam requested changes
PR này không chạy đc, đâu có route đâu?

2019-07-03 06:03 UTC, yeuem1vannam commented on app/dashboards/term_dashboard.rb
> +  :id,
Indent sai

2019-07-03 06:03 UTC, yeuem1vannam commented on app/policies/term_policy.rb
> +  end
- Indent sai
- Policy vô nghĩa

2019-07-10 01:29 UTC, dutavi commented
![Screenshot from 2019-07-10 08-23-56](https://user-images.githubusercontent.com/43242076/60933413-53989180-a2ec-11e9-842b-6bb8f5da82ab.png)

### Cháu thử viết test cho phần Term (Edit_spec.rb) mà chạy báo như này thì theo chú lỗi đến từ đâu chú nhỉ ?

2019-07-10 04:15 UTC, yeuem1vannam commented
@dutavi 
1. Test trong phạm vi nào (scope): admin -> đã có admin ✅ 
2. Test cho cái gì (subject): term -> chưa thấy có tạo term :x:
3. URL nào: admin_term_path -> đây là url của **term**, như vậy đặt `admin_term_path(admin)` là sai :x:
4. Code như thế nào -> code không indent cho đúng, auto sai :x:

2019-07-10 04:38 UTC, dutavi commented
![Screenshot from 2019-07-10 11-37-48](https://user-images.githubusercontent.com/43242076/60940855-30c7a680-a307-11e9-8fd0-15a4f1ebf556.png)

@yeuem1vannam 
-Có term rồi đây chú nhỉ ?

2019-07-10 05:04 UTC, yeuem1vannam commented
1. Trong môi trường test, với mỗi test đều phải tạo các record tương ứng. Ở đây chúng ta dùng `FactoryBot`, như chỗ tạo admin đó 
```ruby
let(:admin) { create :user, :admin }
let(:term) { FactoryBot.create :term } # Trong test hiện tại có thể viết rút gọn `FactoryBot.create' thành `create'
before do
  # do other
  visit admin_term_path(term) # chính là cái nằm trong let(:term) 
end
```
2. `rails console` mặc định là môi trường `development`, nên database hoàn toàn tách biệt với môi trường test.

2019-07-14 00:07 UTC, yeuem1vannam commented on config/routes.rb
> +  resources :terms
Not necessary line

2019-07-14 00:07 UTC, yeuem1vannam commented on spec/features/admin/terms/edit_spec.rb
> +end
Need one more test that ensure normal user cannot access the admin edit page

2019-07-16 02:36 UTC, yeuem1vannam requested changes
Clean up the Pull Request message please

2019-07-16 02:36 UTC, yeuem1vannam commented on app/models/term.rb
> +  validates :word, :meaning, :reading, presence: true
Write test for this please
```ruby
# spec/models/term_spec.rb
it { should validate_presence_of :word }
# ...
```

See more at http://matchers.shoulda.io/docs/v4.1.1/

2019-07-16 02:36 UTC, yeuem1vannam commented on app/policies/term_policy.rb
> +  end
Still?

2019-07-16 02:36 UTC, yeuem1vannam commented on spec/features/admin/terms/edit_spec.rb
> +end
Still?

2019-07-17 07:33 UTC, dutavi commented on app/policies/term_policy.rb
> +  end
What do you mean  ?

2019-07-17 07:51 UTC, yeuem1vannam commented on spec/models/term_spec.rb
> +  it { should validate_presence_of(:reading) }
missing validate length?

2019-07-19 01:54 UTC, yeuem1vannam commented on spec/models/term_spec.rb
> +  #Test_Word :
This comment is not necessary.
It does not improve the readability but also make code less attractive.

This comment style only works when:
- The code below the comment is hard to understand
```ruby
# Find a user with specific flag and transform it
User.all.select { |u| u.flag = :this_is_a_flag }.map { |u| u.name.upcase! }
```
- The data flow is complex
```ruby
# First, split the name by delimiter
klass_names = self.class.name.split("::")
# Second, transform them
klass_names.each { |string| string.downcase! }
# Finally, make the underscore
klass_names.join("_")
```

So, why is this comment bad?

```ruby
RSpec.describe Term, type: :model do # <- reader already understand this is a test
```
```ruby
it { should have_db_index :word } # <- this test is well-understand that for `word`
```

2019-07-19 01:54 UTC, yeuem1vannam commented on spec/models/term_spec.rb
> +  #end.
The block comment style must strictly follow the rule: 
- Must have `begin` before the `end`
- Must indicate with specific block flag
- Must have the same convention: `begin|end` | `/Start|/End` | `NOTE: Start|NOTE: End`
```ruby
# /Start Make Underscore
klass_names = self.class.name.split("::")
klass_names.each { |string| string.downcase! }
klass_names.join("_")
# /End Make Underscore
```

2019-07-19 01:55 UTC, yeuem1vannam approved these changes

2019-07-19 01:55 UTC, merged